### ISSUE TITLE
Version parameter

### ISSUE THREAD

**Issue by chrysn** [core-wg/resource-directory#83] opened 2017-10-30 17:26 UTC
I'm just removing an in-text TODO about adding a version parameter.

Taking this to the issue tracker so it won't get lost -- but IMO we have sufficient ways for extensibility in that both individual features and completely new versions can be announced via the rt. If a client wants to utilize a particular feature, the RD can announce that as `rt="core.rd-res vnd.my-feature"` at the URI discovery step, and if at some point in time a backwards-incompatible successor to RD appears, it will just say `rt="core.rd2"`.

(Assigning to @petervanderstok because you had added that TODO, feel free to close without further comment if this has become obsolete).

**Comment by petervanderstok** [comment] 2017-11-09 08:26
Version was originally suggested by Michael.
To me it looks a reasonable addition that could be added into -13 as a compulsory attribute.
Motivation: Many industrial tools feature versions to learn about things to avoid or not use in this version.

**Comment by petervanderstok** [comment] 2017-11-09 08:26
wrong button

**Comment by chrysn** [comment] 2017-11-10 11:35
But is a dedicated link attribute the superior solution to making the distinction in the rt="core.rd" name?

Or differently put: If we have mandatory versioning and incompatible future versions, does rt="core.rd" still mean anything short of roughly describing the purpose but not how to deal with it?

**Comment by petervanderstok** [comment] 2017-11-27 11:18
putting versioning into rt means a lot of registering of rt values for different versions by companies.
I am not convinced that (mis-)using rt values is the right way forward for versioning

**Comment by petervanderstok** [comment] 2018-01-15 10:00
What about getting the version in the the rd resource path.
On discovery it returns for example
/rd4.2.1 with version and release number
or /rd21092018 to associate a date with the version

We could put some text in section 5.2 just before the examples, and adjust the example accordingly

**Comment by cabo** [comment] 2018-01-15 10:02
Versions are the wrong solution. What was the problem?

**Comment by petervanderstok** [comment] 2018-01-15 10:05
The problem is that most OS and service codes have a version number.
Accordingly one knows which errors can be expected and what feature is 
(not) supported.
Very common facility.

Peter

cabo schreef op 2018-01-15 11:02:

**Comment by cabo** [comment] 2018-01-15 10:40
On Jan 15, 2018, at 11:05, peter van der stok <notifications@github.com> wrote:
> 
> The problem is that most OS and service codes have a version number.

That is indeed a problem.  But one that we can’t fix here.

> Accordingly one knows which errors can be expected and what feature is 
> (not) supported.

Features ≠ versions.

> Very common facility.

And very commonly a source of headaches.

Again, what is the problem we want to solve for RD?

Grüße, Carsten

**Comment by petervanderstok** [comment] 2018-01-15 11:01
The problem was originally introduced by Michael.
And I agreed with the existence.
The RD will be implemented and maintained by a company or alliance.
The original implementation may have mistakes that are resolved in later 
implementations.
The RD specification may evolve, either driven by RFCs or by other SDOs.

It will be nice to see to which implementation cycle or specification 
epoch the implementation of a given server belongs: to know the features 
and mistakes of the used version.

The implementation identification can be done with a version number, 
returned by the server.

Do you have a better idea to identify the implementation evolution?

Cheerio,

peter


cabo schreef op 2018-01-15 11:40:
> On Jan 15, 2018, at 11:05, peter van der stok

**Comment by cabo** [comment] 2018-01-16 23:48
So this is about implementation version, not RD protocol version.  Pretty much like a User-Agent string in HTTP.  We should provide a way to put this into a self-description of an RD, e.g., as a link relationship.

**Comment by petervanderstok** [comment] 2018-01-17 08:04
would be fine as well for me.
Something like /rd/version with contents of version open, version name standardized, and rd an example base value. version can be e.g. 4.3.1, or 20January2017......

**Comment by chrysn** [comment] 2018-01-17 10:20
The software version that implements a particular resource is not something that's particular to the RD, and for describing name and version there is already an established vocabulary (DOAP or, as I just found out, POWDER). The link-format examples already give a relation to use. One could use

    </rd>;rt="core.rd",
    <https://software.example.com/our-rd-server/0.4a1>;rel="describedby";anchor="/rd"

. Whoever wants to evaluate those properties like a client would look at the HTTP Server header can do that, and others just ignore the link.

(Admittedly, the POWDER format specified by W3C for use with describedby is not 1:1 suitable for this purpose as it requires explicit "iriset"s and thus apparently can't be used as RFC6690 seems to suggest, but any other term or file type would do just as well.)

IMO this is something we should not tie into the RD specification, but if one were to sketch up a draft as to how a resource's software implementation can be advertised, that could be informally referenced.

**Comment by petervanderstok** [comment] 2018-01-17 10:29
Fine with me; I have  no strong feelings apart from wanting some text how to handle versions. Recommending the POWDER in RD spec look suitable.

**Comment by chrysn** [comment] 2018-01-25 14:15
Looking a bit deeper into POWDER indicates it's not really actively used ([W3C thread](https://lists.w3.org/Archives/Public/semantic-web/2017Jan/0033.html)), and that describedby has been [abused earlier by others as well](https://github.com/json-ld/json-ld.org/issues/197) (my assumption being that it found its way into RFC6690 examples without full consideration of whether that actually fits).

Due to that I'd not particularly recommend using POWDER, but say for example that

Like any other resource, a Resource Directory MAY provide additional data about itself in the `.well-known/core`; for example, it can make statements about its implementation by publishing `</rd>;rt="core.rd",</descriptions/rd>;rel="describedby";anchor="/rd";ct="0 65123 65456"`, where `/descriptions/rd` can serve a variety of content formats that can, among other things, identify the software name and version providing the `/rd` resource.

**Comment by cabo** [comment] 2018-01-25 16:21
Maybe we should define a new rel just for that, "diagnostic information about implementation" or some such.
Anchor it to the RD so that it is clear that it is about the RD.
Copy the security considerations of the HTTP Server: header field.

**Comment by cabo** [comment] 2018-01-25 16:24
copy considerations from RFC 7231:
7.4.2.  Server
9.6.  Disclosure of Product Information

**Comment by cabo** [comment] 2018-01-25 16:36
describedby is used for other purposes as well.  Maybe we should try to reduce the confusion by defining a new rel-type.
So write a short draft for a new relation type (which might even be informational), borrowing from RFC 7231; we then point to that from the RD spec.

**Closed** 2018-02-01 07:57 UTC
Labels: patch available
