### ISSUE TITLE
Observing lookups operation in the Resource Directory

### ISSUE THREAD

**Issue by onovo1** [core-wg/resource-directory#74] opened 2017-10-25 13:11 UTC
Hi,

Right now, the RD document does not specified an operation to retrieve a lookup query and keep the query updated by the RD over a period of time.

That type of operation would be very useful when CoAP endpoints want to continuously query for the existence of specific resources in the Resource Directory.  

Even though the 'observe' operation can be applied to the GET operation, the RD specification does not specify the possibility of observing a query and the existing RD applications are ignoring that possibility right now. On the other hand, the observe RFC is not strictly defining the 'observation' of queries, it is just specifying the 'observation' of resources.

**Comment by mjkoster** [comment] 2017-10-25 15:37
An Observe option results in a caching of the request and re-transmission of the response payload each time the representation changes. 

This seems to be completely acceptable as an operational definition for a RESTful query that returns a result any time the resultset changes.

Best regards,

Michael

**Comment by chrysn** [comment] 2017-10-26 06:45
The latest editor draft (to be submitted as a draft before the next meeting) already mentions that possibility: "Clients that are interested in a lookup result repeatedly or continuously can use mechanisms like ETag caching, resource observation ([RFC7641]), or any future mechanism that might allow more efficient observations of collections."

**Comment by jaimejim** [comment] 2017-10-26 14:22
This issue is now closed, however wouldn't it be useful to have an example of such lookup in the "Lookup examples" Section? Feel free to close otherwise.


Something along the lines of:
```
 Req: GET /rd-lookup/res?rt=temperature
 Observe: 0
```

Initially the response would be 
`  Res: 2.04`

However after some time and another device registering it would be:
```
 Res: 2.05 Content
 </temp>;rt="temperature";anchor="coap://[2001:db8:3::123]:61616"

```

I think this would help readers and provide a sample reference.

**Comment by onovo1** [comment] 2017-10-27 07:37
I think an example of an 'observe' lookup would make a lot of sense in the text.

**Comment by onovo1** [comment] 2017-10-29 12:48
After thinking things over, I believe that a proper explanation is needed in the document too. Not just an example. 
Right now, the observe is only working for existing resources. Trying to 'observe' a non-existing resource returns a 4.04 response code according to the RFC 7641.

In our case, a resource lookup is doing an 'observe' of resources that don't exist in the system and we expect that the Resource Directory behaves slightly different than a normal observe.  Think about the case of a lookup with a wildcard operator:

```
 Req: GET /rd-lookup/res?rt=temp*
 Observe: 0
```

In the example above, the client expects to obtain information of future resources too.  That really changes the behave of the 'observe' operation and developers won't be able to understand it if it is not explain properly in the document.

**Comment by chrysn** [comment] 2017-10-30 13:00
Oh, the other issue's mention was not mailed around: The 4.04 was an error in the specification, that has just been resolved.

I'm adding an example and leaving the "Clients that are interested [...] can use mechanisms liek ETag caching [and] resource observation" in.

@onovo1, do you think that the [latest text as hosted here](https://core-wg.github.io/resource-directory/draft-ietf-core-resource-directory.html) is sufficiently usable now?

**Comment by onovo1** [comment] 2017-11-01 10:40
Sorry to be picky but I don't entirely agree with the latest text. Right now the text says the following:

> ...These are advertised, detected and used according to their own specifications and can be used with the lookup interface as with any other resource.

This part of the text is not entirely true since, as I tried to explain in my previous message, the observe specification (RFC 7641) is not accepting observations of resources that do not exist, it returns an error. However, the RD does.

What about adding the following text to the document?

> Clients that are interested in a lookup result repeatedly or continuously can use mechanisms like ETag caching, resource observation ([RFC7641]), or any future mechanism that might allow more efficient observations of collections. As opposed to the resource observation specification ([RFC7641]), clients can observe non-existing resources in the Resource Directory. The mechanisms should be designed in such a way that an observe registration to a non-existing resource returns a 2.05 Content and an empty payload. 

> Additionally, the Resource Directory allows the observation of multiple resources at once too since a trailing  “*” wildcard operator can be used in the lookups. 

Do you think it would make sense to add it?

**Comment by chrysn** [comment] 2017-11-02 08:31
> Sorry to be picky

No need to be, thorough vetting is what we're asking for.

> the observe specification (RFC 7641) is not accepting observations of resources that do not exist

My point is: that a lookup could return 4.04 was an honest mistake that has since been removed (in #76). There is nothing non-existing about query lookups any more. (One could be tempted to observe registration resources themselves, which could actually be absent, but the Read Endpoint Links interface is not used any more and will be removed in the next draft.)

Any lookup (endpoint, group or resource) will now succeed with a 2.05 Content, which of course may be link-format document that contains zero links. Thus, I think that it does not deviate from RFC7641 in a noteworthy fashion.

**Comment by onovo1** [comment] 2017-11-02 12:50
Thanks for your email and explanation. 
I agree with you that reporting a 4.04 error was a mistake and I agree with that fixed. However, here I am talking about an slightly different issue. 

The issue is related to observing empty resources. I agree that after the latest fix, it is possible to observe empty resources in the resource directory but the RD document is not clear enough about that. An example is not enough and the text is actually giving the wrong idea. The RD text just say to use observe as is explained in RFC7641: 

> These are .... used according to their own specifications and can be used with the lookup interface as with any other resource.

However, RFC7641 do not accept observations to non-existing resources and the RD -after the latest fix - does. That should be fixed in the text. That's the reason I proposed an alternative text for the RD document in my previous comment.

I have been implementing the RD an it was not clear at all to me how the observation should be done in the RD. For instance, how should behave the RD in an observe wildcard operation? There is no examples either a proper explanation on the document. On the other hand, RFC7641 does not specify lookup operations at all. 
For the other GET operations, if I follow RFC7641 as the RD suggests to do, I should return a 4.04. However, I believe that is not the behaviour you want right now. Just the opposite.

Unfortunately, I am not the only one having this issue. Just check the RD implementations, they don't really accept observations for lookups. That's the reason, the observation should really be explained better. Otherwise, the developers will have a hard time to understand the meaning of observation in the RD.

**Comment by petervanderstok** [comment] 2018-01-26 08:58
Hi
Can this issue #74 from resource directory be closed given the current state of the text?

**Comment by onovo1** [comment] 2018-01-26 10:41
Hi Peter,

I haven't yet received any reply to my concerns. Besides, I think the text is still incoherent with RFC7641. 
I proposed an alternative text but I haven't received any feedback of it and it has not been integrated in the document:

```
Clients that are interested in a lookup result repeatedly or continuously can use mechanisms like ETag caching, resource observation ([RFC7641]), or any future mechanism that might allow more efficient observations of collections. As opposed to the resource observation specification ([RFC7641]), clients can observe non-existing resources in the Resource Directory. The mechanisms should be designed in such a way that an observe registration to a non-existing resource returns a 2.05 Content and an empty payload.
 
Additionally, the Resource Directory allows the observation of multiple resources at once too since a trailing “*” wildcard operator can be used in the lookups.
```

**Comment by mjkoster** [comment] 2018-01-30 03:09
I believe that the confusion arises as to what resource is being observed. 

I suggest we stay away from defining such a thing as a "non-existent" resource, and focus on the operation of observe.

In the case of lookup, it is the lookup resource being observed, and not some non-existent resource that might be retuerned if it happens to come into existence...

If we submit a query like GET /rd/lookup-res/?rt=temperature, and there is nothing that satisfies the query string, an empry result [] will be returned.

If we do the same with observe, the query should be cached by the RD server and a response should be generated whenever a link with "rt=temperature" is either registered or unregistered, that is whenever the result set of the query changes or is otherwise updated (notifications could be sent, for instance, when a link containing "rt=temperature" is updated, assuming link update functionality).

I think we might take the relevant text from RFC7641 and add clarification in the RD draft.

Best regards,

Michael

**Comment by petervanderstok** [comment] 2018-01-30 09:01
I think it is even simpler than that.
RFC 7641 intro states:
"Thus, by designing CoAP resources that change their state on certain
   conditions, it is possible to update the client only when these
   conditions occur instead of supplying it continuously with raw sensor
   data.  By parameterizing resources, this is not limited to conditions
   defined by the server, but can be extended to ++arbitrarily complex
   queries++ specified by the client.  The application designer therefore
   can choose exactly the right level of complexity for the application
   envisioned and devices involved and is not constrained to a "one size
   fits all" mechanism built into the protocol.

The resource is /rd/lookup/res and exists during the lifetime of the RD
The incredibly complex condition is ?rt=temp*.
When nothing satisfies the condition, empty payload is returned at registration
empty or not, the request is registered.
Any time something happens that changes the payload to be returned, the client is updated.
Is that satisfactory text? possibly with different terminology.

**Comment by onovo1** [comment] 2018-01-30 12:27
Thanks Michael and Peter for your responses. I really appreciate it. 

Michael: I see your point, however, I think it would be good to avoid re-defining what is a resource and what is not in the RD's document. That definition could get easily incompatible with existing CoRE RFCs. Besides, implementation-wise, I have a hard time to understand how a lookup request can be a resource in a RD.

Peter: I agree that the resource /rd/lookup/res exists during the lifetime of the RD. However, the resource "/rd/lookup/res?rt=temperature" might not exist in the RD and the  RD's document does not specified how to deal with a lookup of a resource that does not exist in the RD. According to RFC 7641, a 4.04 should be returned:

   ```
However, in the event that the state of a resource changes in
   a way that would cause a normal GET request at that time to return a
   non-2.xx response (for example, when the resource is deleted), the
   server SHOULD notify the client by sending a notification with an
   appropriate response code (such as 4.04 Not Found) and subsequently
   MUST remove the associated entry from the list of observers of the
   resource.
```

I think the solution for specific resource lookups and "wildcard" lookups would be similar to Peter's proposal: if nothing satisfies the condition, a 2.03 (Valid) response code with empty payload is returned and the lookup is not deleted from the server. 

What do you think?

**Comment by petervanderstok** [comment] 2018-01-31 10:03
I have added observe text in 7.3. and committed.
It is pretty explicit: Anyone wants to reduce text size?
Onovo, can you close the issue when satisfied; thanks for your input.

**Comment by chrysn** [comment] 2018-01-31 11:22
I think that the latest text doesn't make thigns any better, as it introduces "existing" resources and that terminology is not helping here.

A resource is what is targeted by a request as identified by its URI, so in a manner of speaking, `/rd-lookup/res` and `/rd-lookup/res?rt=temp*` *are* different resources. Arguing about which of those "exists" is pointless in my opinion, as there is nothing inherently existing about those resources -- the only thing that matters is if a request to the URI succeeds.

If one insists in an "existance" term, all of the resources that start with `/rd-lookup/res?`, with possible exception if somethign constitutes a Bad Request per se, do exist all of the time.

All those addresses can be requested validly, and as the "Success" paragraph in the "RD Lookup" section says, will return a 2.05 Content that contains a payload of zero links.

Using 2.03 here mixes in the orthogonal matter of caching; such a reply can only happen if the client sent an ETag option in the request, and that matches the current resource state. This can happen at *any* RD lookup request, and I think we don't need to write it down explicitly because RFC7252 already describes the matter comprehensively.

@onovo1, did you have a look at the current `Req: GET /rd-lookup/res?rt=light` example in the Lookup examples section? Can we maybe agree on the validity of the example already while we're fleshing out how much we have to write in the specification text to make this the specified behavior?

**Comment by onovo1** [comment] 2018-01-31 14:11
According to the CoAP specification (rfc7252), the definition of resource is taken from RFC2616. RFC2616 defines resource as follows:

```
A network data object or service that can be identified by a URI,
      as defined in section 3.2. Resources may be available in multiple
      representations (e.g. multiple languages, data formats, size, and
      resolutions) or vary in other ways.
```

So, according to that definition, a resource is a network data object. Meaning that `/rd-lookup/res` and `/rd-lookup/res?rt=temp*` are identifiers to the resources rather than resources as such. 

The definition of 'resource discovery' in RFC7252 describes that meaning too when it talks about hosted resources in server. 

```
      The process where a CoAP client queries a server for its list of
      hosted resources (i.e., links as defined in Section 7).
```

@chrysn: I agree that using 2.03 might be inappropriate in this context. A  2.05 Content would be a better option but then, the payload can not be empty. 
I am totally fine with the current lookup example in the document but then, the payload in the answer should not be empty. 

@chrysn @petervanderstok: What about to change the text as follows?

```
Res: 2.05 Content
Observe: 23
Payload: [ ]

```
```
When resource observation is used, the following convention MUST be followed:  

 o  When none of the links matches the filter, an empty payload with
 response code 2.05 (Context) is returned with a payload '[ ]'.
 o  In all other cases, the set of matching links is returned in the
 payload with response code 2.05 (Content).
 o  Every time, the set of matching links changes, or the content of a
 matching link changes, the RD sends a notification with the  
 matching link set.

```

Would that make more sense?

Oscar

**Comment by chrysn** [comment] 2018-01-31 14:40
> Meaning that /rd-lookup/res and /rd-lookup/res?rt=temp* are identifiers to the resources rather than resources as such.

Yes, should have said "*refer to* different resources".

> 2.05 Content would be a better option but then, the payload can not be empty.

Why not?

> Would that make more sense?

Let's come back to that once I understand why the empty payload should not be valid for a 2.05 response.

**Comment by petervanderstok** [comment] 2018-01-31 16:09
apologies, I misread 7641
"If the client included one or more ETag
    Options in the GET request (see Section 3.3), notifications can have
    a 2.03 (Valid) response code rather than a 2.05 (Content) response
    code."
Indeed no 2.03 for RD empty payload

And indeed, why can't the payload be empty?

The text below is shorter, good. Hope we come to an agreement.

Peter

Onovo schreef op 2018-01-31 15:11:

**Comment by onovo1** [comment] 2018-01-31 17:06
Well, now I am not sure. Can a message with an empty payload include the Content-Format field? 
If yes, then, it should be fine to have an empty message. Otherwise, we cannot have an empty message since rfc7641 states that the future notification messages should have the same Content-Format as the initial response.

**Comment by mjkoster** [comment] 2018-01-31 17:11
If the payload is an empty list of links, then it should have a representation in each supported serialization, e.g. for link-format_json it is [] the empty array, which implies a defined content format.

Best regards,

MIchael

**Comment by mjkoster** [comment] 2018-01-31 17:24
The different query URIs, which contain correctly formed queries, e.g. "lookup/res?rt=temp*"  may be thought of as being resurces that exist, because of the existence of the query resource itself. Being representations of query resultts, they may return representations that contain zero or more elements. I believe this is OK. There are valid representations of link formats which contain zero elements.

Obeserving one of these then simply returns the state of the resource, filtered by the query, each time the contents are updated, including the transition from no elements [] to some elements [{...}, {...}].

Best regards,

Michael

**Comment by mjkoster** [comment] 2018-01-31 17:27
> On Jan 31, 2018, at 9:24 AM, Michael Koster <michaeljohnkoster@gmail.com> wrote:
> 
> The different query URIs, which contain correctly formed queries, e.g. "lookup/res?rt=temp*"  may be thought of as being resurces that exist,
...references to resources which exist...
> because of the existence of the query resource itself. Being representations of query resultts, they may return representations that contain zero or more elements. I believe this is OK. There are valid representations of link formats which contain zero elements.
> 
> Obeserving one of these then simply returns the state of the resource, filtered by the query, each time the contents are updated, including the transition from no elements [] to some elements [{...}, {...}].
> 
> Best regards,
> 
> Michael
>

**Comment by chrysn** [comment] 2018-01-31 18:09
@onovo1: I haven't seen any indication that sending a Content-Format and a zero-byte payload would not be legal, and done it a few times (with text/plain). Granted, a zero-byte payload is illegal in some content formats, but particularly in application/link-format, it is valid. (The `link-value-list` ABNF rule has all its body optional in square brackets).

Other content formats don't have that problem anyway, because their "no results" payloads are `[]` and `80` (hex) for JSON and CBOR links.

Therefore, I think we can even shorten the text to

> * In all cases, the set of matching links is returned in the payload with response code 2.05 (Content).

and even that can be elided because that's exactly what the lookup interface specification says for the case of success; what remains is:

> When observation is used on a lookup resource,
> every time the set of matching links changes, or the content of a matching link changes, the RD sends a notification with the new matching link set.

I'm preparing a pull request to that effect.

@mjkoster wrote:
> I believe this is OK. There are valid representations of link formats which contain zero elements.

Well yes, now that you mention it: I think that core-interfaces batches and dynlink sites have long since returned zero-length payloads of application/link-format type in their empty state.

**Comment by chrysn** [comment] 2018-02-15 14:18
The patch just merged indicated that it solves this issue, re-opening: @onovo1, do you think that the merged text addresses your concerns?

**Comment by onovo1** [comment] 2018-02-16 15:21
Hi,
I have seen the following modification:

> When resource observation is used, every time the set of matching links changes, or the content of a matching link changes, the RD sends a notification with the matching link set.

The text does not say anything when the resource observation does not change. What about adding something like that?

>  When none of the links matches the filter, an empty payload with response code 2.05 (Context) is returned

**Comment by chrysn** [comment] 2018-02-24 11:57
"Empty payload" is not correct in all situations, as not all content formats represent the empty set with an empty document.

Those rules are already laid out half a page below the observation details, I've added a more explicit reference to what the notification contains.

**Closed by chrysn** 2018-02-24 11:57 UTC
Labels: expect reporter OK

**Comment by onovo1** [comment] 2018-02-25 10:44
Right, I see that you have clarified the empty payload now in the text too. 
I think now this issue is clear . 
Thanks!
